### ISSUE TITLE
Optimization: Leb128 implementation is too pure and innocent

### ISSUE THREAD

**Issue by cognivore** [yatima-inc/Wasm.lean#13]
# Why?

Our pure implementation is honest to spec (it reads one to one as the algorithm steps in the spec).

Pure binary crunching implementations tend to be *slow*.

Other implementations use binary manipulation tricks. See python implementation, JS implementation and Rust implementation.

They use the same trick, we should figure out how to do bitmaps in Lean and do it too.

# What?

 - [ ] Learn how to write "dirty" code in Lean.
 - [ ] Port dirty implementations to Lean.

**Comment by ixahedron** [comment]
Clarification question: do you think [Int bitwise arithmetics in YatimaStdLib](https://github.com/yatima-inc/YatimaStdLib.lean/blob/main/YatimaStdLib/Int.lean) and now the new LEB128 implementation in #50 closes this too or did you mean something else?

**Comment by cognivore** [comment]
Yes, exactly what I needed, thank you!
