### ISSUE TITLE
Feature: Make sure that multiple result wasm functions are supported across the board

### ISSUE THREAD

**Issue by cognivore** [yatima-inc/Wasm.lean#21]
# Why?

I know for sure that we don't support multiple results in Engine.lean.
It's bad because it's not standard-compliant.

# What?

 - [ ] Go through all the modules that work with functions and results processing (Code and Engine, and Bytes, I think, at the moment of writing) 
 - [ ] Enumerate functions that process results
 - [ ] Make sure that every function supports multiple results

**Comment by ixahedron** [comment]
Done in #28, ensured it really works in tests.
