### ISSUE TITLE
UX: Use ExtractM in "extract function" functions (if needed (!)).

### ISSUE THREAD

**Issue by cognivore** [yatima-inc/Wasm.lean#44]
# Why?

[As mentioned in this commit](https://github.com/yatima-inc/Wasm.lean/pull/38/commits/8b842d994d9b4922071b0f6f673c0f2910f9a2b9), we need to make sure that all the extractors are actual extractors.

# What?

 - [ ] Understand ExtractM API
 - [ ] Figure out which of the "jackal certified" functions are extractors
 - [ ] Refactor them to use the API.

**Comment by ixahedron** [comment]
Closing this for now, as `ExtractM` only passes around named locals and globals for the purposes of matching their symbolic identifiers to indices. I've checked that the rest of the extractor functions don't deal with this issue. If we ever extend the `ExtractM` API, we can reopen.
